### ISSUE TITLE
Some tables in common Japanese IR reports are not detected

### ISSUE THREAD

**Issue by rjyo** [conjuncts/gmft#14]
Thanks for the great lib!

Most Japanese IR reports have the same format, I tried several but non of them have the tables on the first page (summaries) detected.

Here's one of the example. Non of the tables below were detected. Any way to improve this?

<img width="713" alt="image" src="https://github.com/user-attachments/assets/473bdc48-4e67-4c4d-a2d7-23f837498241">

**Comment by conjuncts** [comment]
Hi, thanks for the report.
Sorry, I'm not really able to address this issue (#10). If the table is always in the same position, you can try passing a bbox manually (#9). It's also worth trying [img2table](https://github.com/xavctn/img2table), which is nicely able to detect tables with explicit borders. Eventually I want to support img2table within gmft, but that is down the road.
