### ISSUE TITLE
Dose gmft support borderless tables?

### ISSUE THREAD

**Issue by wushanyun64** [conjuncts/gmft#16]
Hi, I am thinking about using gmft to extract information from borderless table, dose the package currently support it? Thanks!

**Comment by conjuncts** [comment]
It should! Or at least borderless tables similar to those in scientific papers. 

These are a few examples:
https://github.com/conjuncts/gmft/blob/main/notebooks/results/1/0.png
https://github.com/conjuncts/gmft/blob/main/notebooks/results/1/0.csv
https://github.com/conjuncts/gmft/blob/main/notebooks/results/1/1.png
https://github.com/conjuncts/gmft/blob/main/notebooks/results/1/1.csv
