### ISSUE TITLE
Extracted table from PDF page is rotated but it should not be the case

### ISSUE THREAD

**Issue by alexandrefaure** [conjuncts/gmft#19]
Hello there,

I have a PDF file with several pages and I use gmft to extract table for each page.
On the first page, it's fine and the extraction is working correctly.
On the second page (and the next ones), the page is rotated (I can see it because it's a RotatedCroppedTable instead of CroppedTable for the first page).

Is there a way to correct this or to play with parameters when using TableDetector.extract ?
For information, the PDF file is produced from the conversion of a Word file.
[05_BPU_travaux_voirie_SMPBA_modifie_le_06_08_2024.docx](https://github.com/user-attachments/files/16885597/05_BPU_travaux_voirie_SMPBA_modifie_le_06_08_2024.docx)

Thanks so much for your help,
Alex

![Capture d’écran 2024-09-05 092709](https://github.com/user-attachments/assets/20133fb6-ea53-4dc9-9052-7cd4a4b11c82)

**Comment by conjuncts** [comment]
If you know for sure that your pages will not be rotated, try setting the angle parameter:

```python
if isinstance(ct, RotatedCroppedTable):
    ct.angle = 0

ft = formatter.extract(ct)
# ...
```

Let me know how it goes!

**Comment by alexandrefaure** [comment]
Thanks for your answer !

I've tried in my program but it changes nothing I'm afraid...
It's strange because same thing on all other PDFs...

Here is my script in case you see something wrong :

`from gmft.pdf_bindings import PyPDFium2Document
from gmft import CroppedTable, TableDetector

detector = TableDetector()

from gmft import AutoTableFormatter
from gmft import AutoFormatConfig

config = AutoFormatConfig()
config.semantic_spanning_cells = True # [Experimental] better spanning cells
config.enable_multi_header = True # multi-indices
formatter = AutoTableFormatter(config)

def ingest_pdf(pdf_path) -> list[CroppedTable]:
    doc = PyPDFium2Document(pdf_path)

    tables = []
    for page in doc:
        tables += detector.extract(page)
    return tables, doc`
from the Readme of course :)

and the next part :

`output_pdf_file = 'C:\\Users\\afaure\\data\\tests\output_file.pdf'
output_pdf_file = r"C:\Users\afaure\Downloads\3229079det.pdf"
#output_pdf_file = r"C:\Users\afaure\Desktop\IN-24638\Words pourris\05_BPU_travaux_voirie_SMPBA_modifie_le_06_08_2024_exporte_manuellement.pdf"

import time
import json
_total_detect_time = 0
_total_detect_num = 0
_total_format_time = 0
_total_format_num = 0


results = []
images = []
dfs = []
for paper in [output_pdf_file]:
  start = time.time()
  tables, doc = ingest_pdf(paper)
  num_pages = len(doc)
  end_detect = time.time()
  formatted_tables = []
  for i, table in enumerate(tables):
    ft = formatter.extract(table)
    # with open(f'{paper[:-4]}_{i}.info', 'w') as f:
        # f.write(json.dumps(ft.to_dict()))
    try:
      dfs.append(ft.df())
    except Exception as e:
      print(e)
      dfs.append(None)
    formatted_tables.append(ft)
    # cache images, because closing document will prevent image access
    images.append(ft.image())
  end_format = time.time()


  doc.close()
  results += formatted_tables
  print(f"Paper: {paper}\nDetect time: {end_detect - start:.3f}s for {num_pages} pages")
  print(f"Format time: {end_format - end_detect:.3f}s for {len(tables)} tables\n")
  _total_detect_time += end_detect - start
  _total_detect_num += num_pages
  _total_format_time += end_format - end_detect
  _total_format_num += len(tables)
print(f"Macro: {_total_detect_time/_total_detect_num:.3f} s/page and {_total_format_time/_total_format_num:.3f} s/table ")`

**Comment by conjuncts** [comment]
Hmmm, I'll try to take a look.

**Comment by alexandrefaure** [comment]
Thank you ! Tell me if you need more information of course 🙏

**Comment by conjuncts** [comment]
Okay, I finally got to look at the issue. Hopefully this will help:

```python
from gmft import AutoTableDetector, AutoTableFormatter
from gmft.presets import ingest_pdf

formatter = AutoTableFormatter()

tables, doc = ingest_pdf("af1.pdf")
tables[1].image() # rotated
print(tables[1].angle) # was 90
uncorrected = formatter.extract(tables[1]) # doesn't work

tables[1].angle = 0
corrected = formatter.extract(tables[1])
corrected.df() # works for me
```

And I get the correct result to a call to `corrected.visualize()`:

![image](https://github.com/user-attachments/assets/f50529b1-a821-4ca5-878e-9272ad0cf611)


The issue might have been where we were setting `table.angle = 0`. The key is it has to be set *before* passing the table into the formatter.

And finally if you know that all tables must be not rotated, try this:

```python
from gmft.table_detection import RotatedCroppedTable

for table in tables:
    if isinstance(table, RotatedCroppedTable):
        table.angle = 0
# formatter.extract(...)
```

**Comment by alexandrefaure** [comment]
Thanks so much it worked ! Perfect !
Do you think you'll implement something to correct this bug ? In order not to be forced to put the `table.angle = 0` ?

**Comment by conjuncts** [comment]
Glad to hear it. Since this is an issue with the detection model, there is no easy fix but to train a better model. So no permanent fix for the foreseeable future, unfortunately.
