### ISSUE TITLE
download microsoft/table-transformer-detection and timm/resnet18.a1_in1k？

### ISSUE THREAD

**Issue by YuuuuuUoU** [conjuncts/gmft#2]
Manually download microsoft/table-transformer-detection and timm/resnet18.a1_in1k. Which folder should I put it in after downloading?

**Comment by conjuncts** [comment]
They should go into `~/.cache/huggingface/hub/models--microsoft--table-transformer-detection` and `~/.cache/huggingface/hub/models--timm--resnet18.a1_in1k`

However, it's expected that huggingface transformers automatically downloads these files and creates directories - is that not the case?
