### ISSUE TITLE
Type annotations using the pipe symbol (|) for union types are not supported in Python versions earlier than 3.10.

### ISSUE THREAD

**Issue by jiauy** [conjuncts/gmft#21]
some classes or funcs use "|" for type annotations, for example `class CroppedTable: def __init__ and def image` and `class RotatedCroppedTable def image`, which make my running on python3.9 raise Error

**Comment by conjuncts** [comment]
Okay, I finally addressed this issue with 1698a31. I've been developing on python 3.10 and haven't actually tested on 3.9 but let me know what else comes up.
