### ISSUE TITLE
Blogpost

### ISSUE THREAD

**Issue by Datata1** [conjuncts/gmft#29]
Hey @conjuncts,

I'm not sure how else to reach you, but I wanted to let you know that our team recently published a blog post:
https://codesphere.com/articles/ai-table-extraction-gmft

If you're interested, we can connect and would love to get your feedback!

**Comment by conjuncts** [comment]
Thank you reaching out! That is phenomenal.

**Comment by conjuncts** [comment]
Feel free to contact me at galen dot wei at vanderbilt dot edu
