### ISSUE TITLE
SSL error: any way around this?

### ISSUE THREAD

**Issue by etomlins** [conjuncts/gmft#36]
Hi, I have a firewall around the huggingface api on my wifi server I'm using, so it's not able to pull the models from HF. I have the TATR models downloaded locally. Is there any workaround I could do to still use this library?

**Comment by conjuncts** [comment]
The models are stored in these locations: `~/.cache/huggingface/hub/models--microsoft--table-transformer-detection` and `~/.cache/huggingface/hub/models--microsoft--table-transformer-structure-recognition`. They have this file structure 

```
├───blobs
│       544a9ed52f9055381126de68f25982ebee360d14d03c7abd48813b4f25202f73
│       5ad600679662798040286d4d17c626cbffddd755
│       b784cf6d3759e23c6af6d5c52a9db9e34a7b5aaa
│       f581da65a586591124cac9545b09b93e4e8bf28ce3a8357af6ac15ce94fce16b
│
├───refs
│       main
│       no_timm
│
└───snapshots
    ├───b85a88e0a9ad5e1a5f00b122b6d99174710dda8a
    │       config.json (symlink)
    │       model.safetensors (symlink)
    │
    └───f4d4bdc85c3fe4b1fa49658882a5d38bbdd0f343
            config.json (symlink)
            model.safetensors (symlink)
```
The easiest way might be to download the models via huggingface on a machine without the firewall. Then, you could transfer the files over to the above locations.
