### ISSUE TITLE
ModuleNotFoundError: No module named 'pymupdf'

### ISSUE THREAD

**Issue by qianxuanyon** [conjuncts/gmft#39]
ModuleNotFoundError: No module named 'pymupdf'

```bash
File ~/opt/anaconda3/lib/python3.9/site-packages/gmft_pymupdf/bindings_mu.py:5, in <module>
      3 from typing import Generator
      4 import PIL
----> 5 import pymupdf
      7 from PIL.Image import Image as PILImage
      9 from gmft.common import Rect

ModuleNotFoundError: No module named 'pymupdf'
```
The name of this library seems to be fitz

**Comment by conjuncts** [comment]
I know that `import fitz` used to be the way to import pymupdf, but pymupdf's [github](https://github.com/pymupdf/PyMuPDF) would seem to suggest that `import pymupdf` is the recommended way to do it now. It might be a version issue. What happens if you run `pip show pymupdf`?

**Comment by qianxuanyon** [comment]
found my version is not the latest
