### ISSUE TITLE
table recognition by passing bbox

### ISSUE THREAD

**Issue by cspx2** [conjuncts/gmft#9]
Hi, the project looks very interesting!

Is there a way to invoke table recognition without table detection? 
I mean in the case that I already know the bbox of the table and want to use gmft table recognition on that table.

**Comment by conjuncts** [comment]
Sure, try the constructor for CroppedTable:
```def __init__(self, page: BasePage, bbox: tuple[int, int, int, int] | Rect, confidence_score: float, label=0):```

- bbox expects `(xmin, ymin, xmax, ymax)`
- label=0 is for regular tables; label=1 if it is rotated

Then, pass the CroppedTable to a formatter as usual.
